services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    secrets:
      - wp_admin_password
      - db_password
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file: .env
    networks:
      - inception
    restart: always
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"

  redis:
    container_name: redis
    build: ./requirements/redis
    networks:
      - inception
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/wordpress

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
