services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    secrets:
      - wp_admin_password
      - db_password
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file: .env
    networks:
      - inception
    restart: always
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"

  redis:
    container_name: redis
    build: ./requirements/redis
    networks:
      - inception
    restart: always

  ftp:
    container_name: ftp
    build: ./requirements/ftp
    networks:
      - inception
    restart: always
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress:/var/www/html

  adminer:
    container_name: adminer
    build: ./requirements/adminer
    networks:
      - inception
    restart: always
    ports:
      - "8080:8080"

  static_site:
    container_name: static_site
    build: ./requirements/static_site
    networks:
      - inception
    restart: always
    ports:
      - "3000:3000"

  dashboard:
    container_name: dashboard
    build: ./requirements/dashboard
    networks:
      - inception
    restart: always
    ports:
      - "8081:8081"

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/wordpress

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
