#authorize local users to connect
local_enable=YES
write_enable=YES
#user can only write and access his file
chroot_local_user=YES
allow_writeable_chroot=YES
#passive mode for docker
pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110
#to not run in the background
listen=YES
background=NO
seccomp_sandbox=NO
